author: xpm
module: xpmKit
github_url: https://github.com/xcode-project-manager/xpm
copyright: 'Copyright © 2018 Pedro Piñera. All rights reserved.'
readme: README.md
documentation: guides/*.md
skip_undocumented: true
theme: fullwidth
xcodebuild_arguments: [-workspace, 'spm.xcworkspace', -scheme, 'xpmKit']
sdk: macosx
clean: true
min_acl: internal
custom_categories:
  - name: App
    children:
      - Constants
  - name: Commands
    children:
      - Command
      - CommandRegistry
      - DumpCommand
      - UpdateCommand
      - CommandsContext
      - InitCommand
      - GenerateCommand
  - name: Models
    children:
      - BuildConfiguration
      - BuildFiles
      - Target
      - Config
      - Workspace
      - Scheme
      - Project
      - Settings
      - Platform
      - BuildPhase
      - Product
  - name: Errors
    children:
      - ErrorHandler
      - FatalError
  - name: Utils
    children:
      - Logger
      - Printer
      - FileHandler
      - Bundles
      - App
      - Signals
      - Shell
      - Context
      - ResourceLocator
  - name: Protocols
    children:
      - XcodeRepresentable
