notifications:
  email: false
osx_image: xcode9.3
language: objective-c
install:
- bundle install
- swift package update
script:
- bundle exec rake test
- bundle exec rake release
- |
  if [[ $TRAVIS_BRANCH == 'master' ]]
  ./scripts/update-docs
  fi