version: 2
jobs:
  build:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            brew install sqlite3
            bundle install
      - run:
          name: Run tests
          command: bundle exec rake test