name: Documentation

on:
  push:
    paths:
      - docs/**/*
  pull_request:
    paths:
      - docs/**/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12.x
      - name: Install dependencies
        working-directory: ./docs
        run: yarn install --prod --pure-lockfile
      - name: Build
        working-directory: ./docs
        run: yarn docz:build
