name: Tuist Benchmark

on: ['push', 'pull_request']

jobs:
  test:
    name: Build
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ['12.1']
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Build Package
        working-directory: ./tools/tuistbench
        run: swift build
